name: Ubuntu 64-bit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: Run build script
        run: chmod +x build.sh && ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: td/tdlib
